//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alura.BackendChallenge.Compartilhado.Globalizacoes {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalizacoesDeValidacao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalizacoesDeValidacao() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alura.BackendChallenge.Compartilhado.Globalizacoes.GlobalizacoesDeValidacao", typeof(GlobalizacoesDeValidacao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo obrigatório Codigo não foi informado..
        /// </summary>
        public static string CodigoObrigatorio {
            get {
                return ResourceManager.GetString("CodigoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Codigo deve ser um valor entre 1 e 999999..
        /// </summary>
        public static string CodigoValido {
            get {
                return ResourceManager.GetString("CodigoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo obrigatório Descricao não foi informado..
        /// </summary>
        public static string DescricaoObrigatoria {
            get {
                return ResourceManager.GetString("DescricaoObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Descrição deve possuir no máximo 60 caracteres..
        /// </summary>
        public static string DescricaoTamanhoMaximo {
            get {
                return ResourceManager.GetString("DescricaoTamanhoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo obrigatório Titulo não foi informado..
        /// </summary>
        public static string TituloObrigatorio {
            get {
                return ResourceManager.GetString("TituloObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Titulo deve possuir no máximo 30 caracteres..
        /// </summary>
        public static string TituloTamanhoMaximo {
            get {
                return ResourceManager.GetString("TituloTamanhoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uma URL válida deve ser informada..
        /// </summary>
        public static string UrlInvalido {
            get {
                return ResourceManager.GetString("UrlInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo obrigatório URL não foi informado..
        /// </summary>
        public static string UrlObrigatorio {
            get {
                return ResourceManager.GetString("UrlObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo URL deve possuir no máximo 120 caracteres..
        /// </summary>
        public static string UrlTamanhoMaximo {
            get {
                return ResourceManager.GetString("UrlTamanhoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um vídeo cadastrado com o código informado..
        /// </summary>
        public static string VideoCadastrado {
            get {
                return ResourceManager.GetString("VideoCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este vídeo não está cadastrado.
        /// </summary>
        public static string VideoNaoCadastrado {
            get {
                return ResourceManager.GetString("VideoNaoCadastrado", resourceCulture);
            }
        }
    }
}
